### ISSUE TITLE
First round of feedback of the Correlation library

### ISSUE THREAD

**Issue by vancem** [lmolkova/correlation#1]
These are more reactions.  They may not be completely thought through.    However I do like what I see so far.

* Span needs a Finish() API and an end-time.
* Do we need PreciseStartTimeStamp?    Why long vs DateTime?  
* Baggage needs to be tuned for the functional style.
* Tags should be optimized for the few key's case.  (List of key values is fine).  
* Should CorrelationID simply be  key-value baggage?   
* SpanState should probably just be static methods on Span (don't need another class). 
* SpanState needs to protect itself against incorrect usage (you should pass yourself to Pop, and that pops everything and including that Span.  
* I want to understand the value of IEndPointFilter.   
* Should Span() constructor be hidden (start with this see how far we can go).  
* Can we instrument Incomming HTTP requests with DiagnosticSource?   Is that the way to go? 
* I would really like it if this stuff did not depend on ILogger,  Instead Ilogger depends in this stuff.  After all there are potentally many loggers, but only one correlator, so making the correlator know about loggers seems bad.  
* Id creation should be owned by Span (and in particular they should probably not be GUIDS) we should be able to make hierarchical IDs with little problem.  

As general advice, we should look over the Java implementation of open tracing, and where it differs from our we should be happy with those differences.

**Comment by lmolkova** [comment]
Hi Vance, 

Thanks for the feedback!

I have a new version which addresses most of it (see #2)
There are still things to think about:
> I would really like it if this stuff did not depend on ILogger, Instead Ilogger depends in this stuff. After all there are potentally many loggers, but only one correlator, so making the correlator know about loggers seems bad.

First of all, I wanted logs generated by ASP.NET to write correlation details automatically. To achieve it, correlator called Logger.BeginScope, so any logs would have Span scpope.
Another issue logging in correlator solved, was tracing outgoing requests and this is more complicated. Correlator generates span id for the outgoing request and it should be logged to uniquely map outgoing call on service to incoming request on downstream service. We don't expect users to listen to HttpClient DiagnosticSource; moreover, if they do, their listener may be notified before Correlator's one. So if correlator does not log it, it must notify user about outgoing request. In old design, I had IOutgoingRequestNotifier to do this job. This approach requires user to implement interface and register it in app services. so this makes instrumentation more complex, but decouples correlator from Logging.  The problem with this approach is that it solves very specific issue and if I would need to extend correlator to support other RPC calls, I would probably need more notifiers.
Another problem may arise if we decide to support Log records attached to Span as part of opentracing standard, how would user get those logs?  So, basically the problem is: how to notify user about Span events? And it seems we already have DiagnosticSource to do such things. So Spans write about their Start and Finish to DiagnosticSource.
There are several problems with this design from user perspective
- User still need to listen to SpanDiagSource, which makes usage more complicated.
- ILogger.BeginScope: who should call BeginScope on ILogger and when to dispose scopes: someone who litens to it
I believe those problems could be solved if we provide some default listener in ASP.NET.

>Can we instrument Incomming HTTP requests with DiagnosticSource? Is that the way to go?

I have changes incoming request handling to happen in the Middleware. It's the first place in the request processing piepline correlator can hook into. I also assume that users may have their own middlewares and may need Spans there.
So when HostingApplication writes to Logger and DiagnosticSource, Span in already there and it can use it. I still propose ASP.NET to work with spans.

**Comment by vancem** [comment]
I am closing this issue, as the issues raised were addressed.
